### ISSUE TITLE
checkstyle

### ISSUE THREAD

**Issue by jesperpedersen** [My-Wine-Cellar/winecellar-webapp#171]
Integrate https://checkstyle.sourceforge.io/ into the build

**Comment by pauldpearson** [comment]
https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by dnsmnds** [comment]
Hi Jesper and Paul,

There are two checkstyle file sample at https://github.com/checkstyle/checkstyle/tree/master/src/main/resources

Do you have some opinion on which we should be following for now?

**Comment by jesperpedersen** [comment]
I would start with one of them (f.ex. sun_checks.xml) and then adapt it to our current code style. Any conflicts will be discussed here.

Feel free to assign it to yourself if you are up for it.

**Comment by dnsmnds** [comment]
I agree with you Jesper. Then I'll assign that to me.

**Comment by jesperpedersen** [comment]
If you could integrate the license header to each file as part of this it would be great.

Thanks !

**Comment by dnsmnds** [comment]
Sure I'll find out how to add license header rule to check style.

**Comment by dnsmnds** [comment]
Paul and Jesper, do you have a set license header yet?

**Comment by dnsmnds** [comment]
I think we could use the same header this file https://github.com/eclipse/hono/blob/master/core/src/main/java/org/eclipse/hono/util/AmqpErrorException.java because they are using the same license we have into LICENSE file.

**Comment by jesperpedersen** [comment]
Lets just keep it short
```
/*
 * My-Wine-Cellar, copyright 2019
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 */
```

You would of course need to change `2019` into `\d\d\d\d` for the check

**Comment by jesperpedersen** [comment]
Initial support has been merged, but there are failures, so not enable yet as part of compile

**Comment by dnsmnds** [comment]
Cool! Thanks Jesper. Do you think we need to add a quote in README.md about it?
For instance: How to run a checkstyle task to make sure fix all errors from checkstyle before to send a PR.

**Comment by jesperpedersen** [comment]
Not at the moment since it isn't part of the official build. Once it is we need a coding guideline document which describes the style.

**Comment by dnsmnds** [comment]
Right, are you going to keep that issue open to discuss about coding guideline document?

**Comment by jesperpedersen** [comment]
Yes, we will resolve once everything is done
