### ISSUE TITLE
Image support for producer and wine

### ISSUE THREAD

**Issue by pauldpearson** [My-Wine-Cellar/winecellar-webapp#204]

**Comment by pauldpearson** [comment]
try to center the image upload portion

is there a way to check for file size?

**Comment by jesperpedersen** [comment]
The Bottle part should be moved to Wine, and the Image link should be in wineDetails.html

**Comment by jesperpedersen** [comment]
I would put the images next to the overall description box to left.
```
--------------------------
| Image |  Poggio Antico |
|            |  Phone: ...        |
```

and so on

**Comment by jesperpedersen** [comment]
We should have a size check, but it isn't important now, so it could be a separate task
