### ISSUE TITLE
Gradle and PostgreSQL version

### ISSUE THREAD

**Issue by dnsmnds** [My-Wine-Cellar/winecellar-webapp#209]
I'd like to know which Gradle and PostgreSQL version are you using?

**Comment by jesperpedersen** [comment]
PostgreSQL 9.4 or higher is required at the moment (we will switch to PostgreSQL 12+ once we get to the geo-stuff).

For Gradle we use the wrapper in the project (`./gradlew.sh clean bootRun`), which is at version 4.10 at the moment.

Would you like to submit an update to README.md that clarifies this ?

**Comment by dnsmnds** [comment]
Thanks Jesper.

Yes, I would! I think that is going to be useful to new contributors.
