### ISSUE TITLE
CI/CD switch to new tool

### ISSUE THREAD

**Issue by pauldpearson** [My-Wine-Cellar/winecellar-webapp#217]
Travis or Circle CI

**Comment by jesperpedersen** [comment]
GitHub Actions will be GA soon

**Comment by jesperpedersen** [comment]
https://github.com/My-Wine-Cellar/winecellar-webapp/actions/new

**Comment by pauldpearson** [comment]
We can/should remove the badges for code build and sonar cloud on this merge
