### ISSUE TITLE
bug when registering a new user at /register

### ISSUE THREAD

**Issue by dnsmnds** [My-Wine-Cellar/winecellar-webapp#254]
When I'm trying to register a new user after use `gradle bootRun` I'm getting that error in console:

```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey"
  Detail: Key (id)=(1) already exists.
```

There are 3 rows in users table which it was created from https://github.com/My-Wine-Cellar/winecellar-webapp/blob/master/src/main/resources/sql/01_security.sql

Route:
/register

Versions:
psql (PostgreSQL) 12.0 (Debian 12.0-2.pgdg100+1)

**Comment by jesperpedersen** [comment]
Likely need to set the Hibernate sequence to 4

**Comment by dnsmnds** [comment]
I think so, some thing like that:

```java
@GeneratedValue(generator = "sequence-generator")
@GenericGenerator(
      name = "sequence-generator",
      strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
      parameters = {
        @Parameter(name = "sequence_name", value = "user_sequence"),
        @Parameter(name = "initial_value", value = "4"),
        @Parameter(name = "increment_size", value = "1")
        }
    )
```

Source: https://www.baeldung.com/hibernate-identifiers

**Comment by jesperpedersen** [comment]
Try it out and send a PR

**Comment by dnsmnds** [comment]
It's done! Any problems please let me know.
